name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - '10'
          - '12'
          - '14'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.13.5
          run_install: |
            - recursive: true
      - run: pnpm recursive run lint:check
      - run: pnpm recursive test
